name: CD - Producao

on:
  pull_request:
    types: [closed] # Executa quando o PR para main Ã© merged
    branches:
      - main

env:
  IMAGE_NAME_PRODUCAO: alarme_cicd # Nome da imagem para producao no Docker Hub (pode ser o mesmo de antes se desejar sobrescrever)
  AZURE_WEBAPP_NAME_PRODUCAO: alarme-cicd # Nome do Web App de producao no Azure (o mesmo de antes)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image (Opcional - se houver commits diretamente em main)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_PRODUCAO }}:latest

      - name: Deploy to Azure Web App Producao
        id: deploy-to-webapp-producao
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_PRODUCAO }}
          publish-profile: ${{ secrets.AZURE_PROFILE }} # Mesmo Secret de antes
          images: 'ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME_PRODUCAO }}:latest'